### ISSUE TITLE
asterisk13: Please add AMR and AMR-WB support

### ISSUE THREAD

**Issue by hailfinger** [openwrt/telephony#252] opened 2018-01-25 18:06 UTC
Maintainer: @jslachta 
Environment: mips_24kc, arcadyan_vgv7510kw22, OpenWrt trunk (2018-01-24)

Description:
The asterisk13 package is currently shipped without AMR and AMR-WB support (those codecs are also not part of upstreak asterisk13). Patches for AMR/AMR-WB support are available here: https://github.com/traud/asterisk-amr

**Comment by micmac1** [comment] 2018-01-27 11:06
Hello @hailfinger,

I'm not the maintainer of Asterisk. Apart from that I wouldn't say asterisk13 is currently missing AMR support. I would say AMR support is simply not included in Asterisk. I checked the github repo you linked. Personally I don't like the approach that one should need to patch Asterisk. One reason being that Asterisk and the linked module have different licenses. 

If the code can be compiled externally that would be good. opencore-amr would also need to be packaged for transcoding support. Which shouldn't be an issue as Debian has the package as well. I could even use that in freeswitch-stable.

Just my 2 cents.

Regards,
Sebastian

**Comment by hailfinger** [comment] 2018-01-29 21:42
Hello @micmac1,

my apologies. I had looked for the person committing the most recent asterisk patches instead of checking PKG_MAINTAINER.

Hello @jslachta,

how hard would it be to cleanly integrate (possibly as external build) AMR support into asterisk-13.x? I noticed that the OpenWrt fdk-aac package apparently provides the opencore-amr dependency of this feature.
Regards,
Carl-Daniel

**Comment by micmac1** [comment] 2018-01-29 22:09
Hello @hailfinger,

fdk-amr provides libfdk-aac.so. But for mod-amr the following libs would be needed:

- libopencore-amrnb.so 
- libopencore-amrwb.so
- libvo-amrwbenc.so

The first two are in opencore-amr, the third is in vo-amrwbenc. So two more packages would be needed to provide the missing libs (they're not available in OpenWrt as of now).

These libs would need BUILD_PATENTED=y. So in actuality these packages would never be actually built by the build bots (the default is BUILD_PATENTED=n). Which begs the question if it's really worth the effort of maintaining two more packages and the mod-amr patch on top. How many people would download all this stuff and build it at home? How many people really need amr? I don't think this is worth the effort.

**Comment by hailfinger** [comment] 2018-01-30 08:05
Hello @micmac1,
thank you for looking into this. You're correct, I had mistakenly assumed that a package listing opencore-amr in its makefile would also ship the libraries. I will have to look into packaging this.

I'm using a DSL line provided by O2 in Germany. Telephony is done via SIP. O2 recently stopped transcoding incoming and outgoing calls, so if I get an incoming call from a cell phone, the only codecs offered by the remote end (O2) of my SIP connection are those supported by the calling cell phone. A-law and u-law are not among them. (They are available if the caller is using a landline connection.) Supporting GSM codecs (HR/FR/EFR) in Asterisk takes care of being able to establish a call, but anything with better quality (especially VoLTE calls with AMR-WB) is being downgraded to FR (if supported by the handset) unless AMR is supported. The provider-supplied VoIP/DSL routers support the full set of codecs AFAICS.
Due to that, I expect the interest in AMR support to rise over time, at least for O2 customers in Germany. I have no idea about the number of OpenWrt users running Asterisk on an O2 DSL line in Germany, though.

**Comment by traud** [comment] 2018-01-30 09:35
Thanks for triggering me, I am very interested in your findings. Therefore some (totally different) questions first:

> A-law and u-law are not among them.

I am in Germany as well. I would like to reproduce that issue. Do you know the phone model (firmware version and branding variant) of your remote party? Which radio-access technology does he use (WiFi, LTE, UMTS, or GSM)? Or, do you face that issue with several remote parties?

> Supporting GSM codecs (HR/FR/EFR) in Asterisk …

Currently out-of-the-box, Asterisk supports only GSM-FR. My GitHub contains a patch for GSM-EFR. Because I had no GSM-HR endpoint yet, I did not add GSM-HR yet. Therefore, again, this would be very interesting. Do you get GSM-HR just with some of your remote parties or with many/all?

> The provider-supplied VoIP/DSL routers support the full set of codecs …

Which Internet-access device (IAD) was given to you? O₂ Homebox 6441 or 6641? If possible, please, provide the SDP you get from O₂ DSL and post it here or/and in [this thread…](http://www.telefon-treff.de/showthread.php?threadid=591789) if you need more details how to obtain these information or some cannot be determined right a way, no worry! Simply add the information you have and ask what you need to collect the remaining puzzle pieces.

**Comment by micmac1** [comment] 2018-01-30 11:03
@hailfinger 

You can always switch providers :) There are providers who transcode AMR WB to G722 for their landline customers.

Anyway, I've set up a branch for you: [AMR-for-hailfinger](https://github.com/micmac1/telephony/commits/amr-for-hailfinger). Try it out and let us know how it goes.

Regards,
Seb

**Comment by traud** [comment] 2018-01-30 11:40
At least in Germany, switching providers is not that easy. Normally you have a two-year contract with add-ons which allow free calling of other landline phones nationwide. Therefore, switching provider means loosing money. Furthermore in case of O₂ DSL, you are even able to call certain mobile phones for free as well. Finally, interconnection of HD voice is still at start – you might loose HD voice with that different provider.

However, I have to admit, the 3GPP specifications mandate the support of A-law and µ-law for mobile phones. Therefore, this is an upstream issue actually. Anyway, it might be worth looking at. Therefore, my questions.

**Comment by micmac1** [comment] 2018-01-30 12:33
I updated the patches for Asterisk 13 and 15 to @traud's master (I had previously just copied the patch from Debian). I also added the res-format-attr-amr module. You might want to try with that.

**Comment by hailfinger** [comment] 2018-01-30 22:39
Some of my logs turned out to have been truncated, so I can't give you all the info you want, but I'll try. 
Here is the verbose asterisk log of a call setup originating from a Motorola Moto G2 (unbranded, DE retail) using the blau.de provider booked into UMTS at the time of call:
```[Jan 30 09:34:02] VERBOSE[1928] chan_sip.c:
<--- SIP read from UDP:195.71.31.47:5060 --->
INVITE sip:4922812345678@77.181.123.45:5060 SIP/2.0
Max-Forwards: 68
Via: SIP/2.0/UDP 195.71.31.47:5060;branch=z9hG4bKg3Zqkv7icsr13v49obmvqzmlrmiw8b5nx
To: "4922812345678 VoIP" <sip:4922812345678@sip.alice-voip.de>
From: "01711234567" <sip:01711234567@sip.alice-voip.de;user=phone>;tag=h7g4Esbg_262981723-1517304842760-
Call-ID: BW1034027603001181224836070@10.30.225.185
CSeq: 590693637 INVITE
Contact: <sip:sgc_c@195.71.31.47;transport=udp>
Accept-Contact: *;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel"
Call-Info: <sip:10.30.225.185>;appearance-index=1
Min-Se: 900
P-Asserted-Identity: "+491711234567" <sip:01711234567@ims.telefonica.de;user=phone>
P-Called-Party-ID: <sip:4922812345678@sip.alice-voip.de>
Privacy: none
Session-Expires: 1800;refresher=uac
Supported: timer
Content-Type: application/sdp
Content-Disposition: session;handling=required
Content-Length: 735
Recv-Info: x-broadworks-client-session-info
[Jan 30 09:34:02] VERBOSE[1928] chan_sip.c: --- (25 headers 24 lines) ---
[Jan 30 09:34:02] VERBOSE[1928] chan_sip.c: Sending to 195.71.31.47:5060 (NAT)
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Sending to 195.71.31.47:5060 (NAT)
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Using INVITE request as basis request - BW1034027603001181224836070@10.30.225.185
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found peer 'alice-unauthenticated-host1' for '01711234567' from 195.71.31.47:5060
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] netsock2.c: Using SIP RTP CoS mark 5
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found RTP audio format 100
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found RTP audio format 101
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found RTP audio format 9
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found RTP audio format 102
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found RTP audio format 103
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found RTP audio format 104
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found RTP audio format 8
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found RTP audio format 105
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found RTP audio format 106
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found unknown media description format AMR-WB for ID 100
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found unknown media description format AMR-WB for ID 101
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found audio description format G722 for ID 9
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found unknown media description format AMR for ID 102
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found unknown media description format AMR for ID 103
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found unknown media description format AMR for ID 104
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found audio description format PCMA for ID 8
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found audio description format telephone-event for ID 105
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Found unknown media description format telephone-event for ID 106
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Capabilities: us - (ulaw|alaw|gsm|h263), peer - audio=(alaw|g722)/video=(nothing)/text=(nothing), combined - (alaw)
[Jan 30 09:34:02] VERBOSE[1928][C-00000000] chan_sip.c: Non-codec capabilities (dtmf): us - 0x1 (telephone-event|), peer - 0x1 (telephone-event|), combined - 0x1 (telephone-event|)```

This call worked fine. I get the same call setup log when calling from a Motorola Moto E2 (unbranded, DE retail) using another O2 reseller booked into UMTS at the time of call. Note that for those calls the SDP contained an A-law entry.

**Comment by hailfinger** [comment] 2018-01-30 22:44
I will use tcpdump to retrieve the SDP I get from O2 DSL during those calls.

Side note: The native Android SIP client via Wifi sends a SDP containing GSM-EFR, AMR, GSM, PCMU, PCMA. Will try to get a tcpdump for that as well.

**Comment by hailfinger** [comment] 2018-01-31 07:05
SDP for the incoming cell phone call:
```
INVITE sip:4922812345678@77.181.123.45:5060 SIP/2.0
Max-Forwards: 68
Via: SIP/2.0/UDP 195.71.31.47:5060;branch=z9hG4bKg3Zqkfoobar
To: "4922812345678 VoIP" <sip:4922812345678@sip.alice-voip.de>
From: "01711234567" <sip:01711234567@sip.alice-voip.de;user=phone>;tag=h7g4Esbg_1521736615-1517381862377-
Call-ID: BW075742377310118109432744@10.30.225.185
CSeq: 629203445 INVITE
Contact: <sip:sgc_c@195.71.31.47;transport=udp>
Accept-Contact: *;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel"
Call-Info: <sip:10.30.225.185>;appearance-index=1
Min-Se: 900
P-Asserted-Identity: "+491791234567" <sip:01711234567@ims.telefonica.de;user=phone>
P-Called-Party-ID: <sip:4922812345678@sip.alice-voip.de>
Privacy: none
Session-Expires: 1800;refresher=uac
Supported: timer
Content-Type: application/sdp
Content-Disposition: session;handling=required
Content-Length: 735
Recv-Info: x-broadworks-client-session-info
Allow: ACK, BYE, CANCEL, INFO, INVITE, OPTIONS, PRACK, REFER, NOTIFY, UPDATE
Accept: application/dtmf-relay
Accept: application/media_control+xml
Accept: application/sdp
Accept: multipart/mixed

v=0
o=BroadWorks 259938600 1 IN IP4 195.71.31.47
s=-
c=IN IP4 62.52.129.19
t=0 0
m=audio 56236 RTP/AVP 100 101 9 102 103 104 8 105 106
b=AS:80
a=rtpmap:100 AMR-WB/16000
a=fmtp:100 mode-set=0,1,2; mode-change-period=2; mode-change-neighbor=1; max-red=0
a=rtpmap:101 AMR-WB/16000
a=fmtp:101 mode-change-capability=2; max-red=0
a=rtpmap:9 G722/8000
a=rtpmap:102 AMR/8000
a=fmtp:102 mode-set=0,2,5,7; mode-change-period=2; mode-change-neighbor=1; max-red=0
a=rtpmap:103 AMR/8000
a=fmtp:103 mode-set=7; max-red=0
a=rtpmap:104 AMR/8000
a=fmtp:104 mode-set=0,2,5,7; max-red=0
a=rtpmap:8 PCMA/8000
a=rtpmap:105 telephone-event/8000
a=rtpmap:106 telephone-event/16000
a=ptime:20
a=maxptime:30
a=bsoft: 1 image udptl t38
```

**Comment by traud** [comment] 2018-01-31 08:50
Yes, thanks! Please, post just the SDP part, everything after that double carriage return behind the Accept lines. Otherwise, too much of your private information is revealed. And that SDP part is the one which what matters for me.

I know the Google Android SIP client and my two modules were tested with that. What I/we need would be a SDP of a call which
A) does not include A-law, and/or
B) includes GSM-EFR, and/or
C) includes GSM-HR.

Perhaps your remote party must be using VoLTE or VoWiFi for that. Currently, I am aware only of O₂ contracts and O₂ LOOP, which allowed for that radio-access technologies within the Telefonica Germany network. The list of supported devices for that can be found on the O₂ webpages. Especially for VoWiFi, the list is terrible short. Anyway, that puzzle piece might help to capture such a problematic SDP.

**Comment by hailfinger** [comment] 2018-02-01 17:21
@traud: The only GSM-EFR in my logs is from the builtin Android SIP client connecting to Asterisk locally.

**Comment by hailfinger** [comment] 2018-02-01 17:31
@traud: Here is a SDP which does not include A-law. It is sent from O2 SIP server to my local Asterisk as response to an earlier INVITE sent by my local Asterisk.

```
v=0
o=BroadWorks 257605788 1 IN IP4 195.71.31.47
s=-
c=IN IP4 62.52.129.19
t=0 0
m=audio 58798 RTP/AVP 9 101
b=AS:80
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=ptime:20
a=maxptime:30
a=bsoft: 1 image udp
```

**Comment by micmac1** [comment] 2018-02-17 10:07
Hi @hailfinger ,

This issue seems to have gone cold. Let's close this. In examples above G722 was offered, so that's a good (wideband) alternative.

Regards,
Seb

**Closed by micmac1** 2018-02-17 10:07 UTC

**Comment by traud** [comment] 2018-02-17 12:14
> a SDP which does not include A-law. It is sent from O2 SIP server to my local Asterisk as response to an earlier INVITE sent by my local Asterisk.

That is a Re-INVITE. The remote party has chosen one of your offerings and limits the remaining call to that audio codec. That is valid behavior. If I misunderstood this, please, do not hesitate to correct me. To find an use-case for your change, you have to find a scenario in which you end-up with no matching codec – that means there is no PCMU, no PCMA and no G.722.

At the start, you mentioned situations when no call could be established. Let us concentrate on that, rather than on SDP posting:
* Do you still see that behavior?
* Do you know the involved networks/devices? You use O₂ DSL in Germany with Asterisk 13. What is your remote party?

**Comment by traud** [comment] 2018-07-05 13:04
When you ended up with no matching codecs, do you remember what your remote party was (which network, which device)?
