### ISSUE TITLE
asterisk11 SIGSEGV if start sip call

### ISSUE THREAD

**Issue by urobasa** [openwrt/telephony#173] opened 2017-08-03 00:00 UTC
1) LEDE Reboot SNAPSHOT r4658-4787e1960b / LuCI Master (git-17.214.30899-bf407f0) 
2) Netgear WNDR3700
3) sip call on local net
4) install asterisk11, add 2 sip to sip.conf
[5000]
type=friend
host=dynamic
username=5000
secret=1234
context=from-sip-lines

[5001]
host=dynamic
type=friend
username=5001
secret=1234
context=from-sip-lines

add to extensions.conf
[from-sip-lines]
exten => _5XXX,1,Dial(SIP/${EXTEN})
exten => _5XXX,n,Hangup()

register in 2 sip clients ext 5000 and 5001, ext registered and online. Call 5000 to 5001, or 5001 to 5000 asterisk SIGSEGV

 do_page_fault(): sending SIGSEGV to asterisk for invalid write access to 7713c000
[ 3986.343530] epc = 77a0688c in libc.so[77994000+92000]
[ 3986.348623] ra  = 77399edf in chan_sip.so[7737e000+9a000]

 do_page_fault(): sending SIGSEGV to asterisk for invalid write access to 76c12000
[ 3546.831077] epc = 774dc88c in libc.so[7746a000+92000]
[ 3546.836170] ra  = 76e6fedf in chan_sip.so[76e54000+9a000]

 do_page_fault(): sending SIGSEGV to asterisk for invalid write access to 77620000
[ 3428.603806] epc = 77eea88c in libc.so[77e78000+92000]
[ 3428.608896] ra  = 7787dedf in chan_sip.so[77862000+9a000]

5) integrate asterisk11  in build image -> The same eggs side view (call - asterisk - SIGSEGV)

**Comment by micmac1** [comment] 2017-08-04 18:34
Hello @urobasa 

Can you please try revision 2 from the mirrors and close this issue if resolved?

Regards,
Seb

**Comment by urobasa** [comment] 2017-08-28 21:12
Hello micmac1
correction is not accepted in the night image of LEDE

**Comment by micmac1** [comment] 2017-08-29 06:50
Are you sure? The change is in trunk and in the current snapshots. I tested it and it worked.

Am 28. August 2017 23:13:00 MESZ schrieb urobasa <notifications@github.com>:
>Hello micmac1
>correction is not accepted in the night image of LEDE

**Comment by urobasa** [comment] 2017-08-29 22:28
http://downloads.lede-project.org/snapshots/targets/ar71xx/generic/lede-ar71xx-generic-wndr3700-squashfs-sysupgrade.bin Tue Aug 29 06:23:36 2017
install asterisk11_11.25.1-2_mips_24kc.ipk
set simple config
call - 
Disconnected from Asterisk server
Asterisk cleanly ending (0).
Executing last minute cleanups
Asterisk ending (0).

**Comment by micmac1** [comment] 2017-08-30 06:06
I don't see a segfault.

Am 30. August 2017 00:28:38 MESZ schrieb urobasa <notifications@github.com>:
>http://downloads.lede-project.org/snapshots/targets/ar71xx/generic/lede-ar71xx-generic-wndr3700-squashfs-sysupgrade.bin
>Tue Aug 29 06:23:36 2017
>install asterisk11_11.25.1-2_mips_24kc.ipk
>set simple config
>call - 
>Disconnected from Asterisk server
>Asterisk cleanly ending (0).
>Executing last minute cleanups
>Asterisk ending (0).

**Comment by micmac1** [comment] 2017-08-30 06:10
Ahaha,

Sorry, I was just looking at the post in my email client and it only showed the first part.

Regards,
Seb

Am 30. August 2017 08:06:48 MESZ schrieb Sebastian Kemper <sebastian_ml@gmx.net>:
>I don't see a segfault.
>
>Am 30. August 2017 00:28:38 MESZ schrieb urobasa
><notifications@github.com>:
>>http://downloads.lede-project.org/snapshots/targets/ar71xx/generic/lede-ar71xx-generic-wndr3700-squashfs-sysupgrade.bin
>>Tue Aug 29 06:23:36 2017
>>install asterisk11_11.25.1-2_mips_24kc.ipk
>>set simple config
>>call - 
>>Disconnected from Asterisk server
>>Asterisk cleanly ending (0).
>>Executing last minute cleanups
>>Asterisk ending (0).

**Comment by micmac1** [comment] 2017-08-30 06:18
Can you post output of

opkg list-installed | grep asterisk

Am 30. August 2017 08:10:22 MESZ schrieb Sebastian Kemper <sebastian_ml@gmx.net>:
>Ahaha,
>
>Sorry, I was just looking at the post in my email client and it only
>showed the first part.
>
>Regards,
>Seb
>
>Am 30. August 2017 08:06:48 MESZ schrieb Sebastian Kemper
><sebastian_ml@gmx.net>:
>>I don't see a segfault.
>>
>>Am 30. August 2017 00:28:38 MESZ schrieb urobasa
>><notifications@github.com>:
>>>http://downloads.lede-project.org/snapshots/targets/ar71xx/generic/lede-ar71xx-generic-wndr3700-squashfs-sysupgrade.bin
>>>Tue Aug 29 06:23:36 2017
>>>install asterisk11_11.25.1-2_mips_24kc.ipk
>>>set simple config
>>>call - 
>>>Disconnected from Asterisk server
>>>Asterisk cleanly ending (0).
>>>Executing last minute cleanups
>>>Asterisk ending (0).

**Comment by urobasa** [comment] 2017-08-30 08:08
opkg list-installed | grep asterisk
asterisk11 - 11.25.1-2
asterisk11-chan-dahdi - 11.25.1-2
asterisk11-codec-a-mu - 11.25.1-2
asterisk11-codec-alaw - 11.25.1-2
asterisk11-codec-dahdi - 11.25.1-2
asterisk11-codec-gsm - 11.25.1-2
asterisk11-codec-resample - 11.25.1-2

**Comment by urobasa** [comment] 2017-08-30 08:26
LEDE kernel: [73682.338898] asterisk[26834]: segfault at 0 ip b703f071 sp b68873e4 error 4 in res_rtp_asterisk.so[b7017000+44000]

**Comment by urobasa** [comment] 2017-08-30 21:38
if i git clone lede and build - no errors

**Comment by micmac1** [comment] 2017-08-30 22:04
It's weird. With a downloaded snapshot base system I get the same. When I install a locally compiled asterisk it still segfaults.

Am 30. August 2017 23:38:02 MESZ schrieb urobasa <notifications@github.com>:
>if i git clone lede and build - no errors

**Comment by urobasa** [comment] 2017-08-30 22:47
we will assume that the error sigsegv is fixed 
and close this issue

**Comment by micmac1** [comment] 2017-08-31 06:17
I think the original issue is fixed and what you spotted later is a different issue. For one we can see that the segfault occurs in a different place (earlier in chan-sip, now in the rtp module).

So a new issue should be raised for the rtp module segfault. I think also that it would be good to check if the same occurs in Asterisk 13, because 13 will be here for a while, whereas 11 will be end of life soon.

By the way, is anything holding you back upgrading from 11 to 13, e.g. a missing module?

Regards,
Seb

Am 31. August 2017 00:47:36 MESZ schrieb urobasa <notifications@github.com>:
>we will assume that the error sigsegv is fixed 
>and close this issue

**Comment by jslachta** [comment] 2017-08-31 06:37
Hi @urobasa,

would you be so kind to test it on asterisk-13.x? I am currently unable to reproduce this issue with your config on chan_sip neither on chan_pjsip.

Please consider switching to asterisk-13.x. The 11.x version won't be held for a long time after its end-of-life (25th of October 2017). 

Kind regards,
Jiri

**Comment by micmac1** [comment] 2017-08-31 06:43
Hi Jiri,

Could you please let me know on which target you cannot reproduce this? Urobasa and me are using mips24. Were you using a different target? What is the snapshot date?

Regards,
Seb

Am 31. August 2017 08:37:25 MESZ schrieb Jiri Slachta <notifications@github.com>:
>Hi @urobasa,
>
>would you be so kind to test it on asterisk-13.x? I am currently unable
>to reproduce this issue with your config on chan_sip neither on
>chan_pjsip.
>
>Please consider switching to asterisk-13.x. The 11.x version won't be
>held for a long time after its end-of-life (25th of October 2017). 
>
>Kind regards,
>Jiri

**Comment by micmac1** [comment] 2017-08-31 06:45
Ah sorry, you said you tested on 13. Never mind :-)

Am 31. August 2017 08:43:02 MESZ schrieb Sebastian Kemper <sebastian_ml@gmx.net>:
>Hi Jiri,
>
>Could you please let me know on which target you cannot reproduce this?
>Urobasa and me are using mips24. Were you using a different target?
>What is the snapshot date?
>
>Regards,
>Seb
>
>Am 31. August 2017 08:37:25 MESZ schrieb Jiri Slachta
><notifications@github.com>:
>>Hi @urobasa,
>>
>>would you be so kind to test it on asterisk-13.x? I am currently
>unable
>>to reproduce this issue with your config on chan_sip neither on
>>chan_pjsip.
>>
>>Please consider switching to asterisk-13.x. The 11.x version won't be
>>held for a long time after its end-of-life (25th of October 2017). 
>>
>>Kind regards,
>>Jiri

**Comment by urobasa** [comment] 2017-08-31 08:08
asterisk13 
upgrading from 11 to 13, I am held back by the absence of asterisk13-chan-dongle

**Comment by micmac1** [comment] 2017-08-31 08:24
I'll check tonight if that can be added.

Am 31. August 2017 10:08:31 MESZ schrieb urobasa <notifications@github.com>:
>asterisk13 
>upgrading from 11 to 13, I am held back by the absence of
>asterisk13-chan-dongle

**Comment by micmac1** [comment] 2017-08-31 08:26
Wait, I already added it a few days ago :-) Can you try it out? It's already built.

Am 31. August 2017 10:08:31 MESZ schrieb urobasa <notifications@github.com>:
>asterisk13 
>upgrading from 11 to 13, I am held back by the absence of
>asterisk13-chan-dongle

**Comment by urobasa** [comment] 2017-08-31 12:52
Oh yes, you are doing magic, fulfilling unspoken desires.

**Comment by jslachta** [comment] 2017-10-29 17:36
Hi,

asterisk at the version 11.x hit its EOL and it is no longer available in this repository and no longer supported by the mainstream. If this issue persists on the asterisk 13.x version, please fill a new ticket for this version.

**Closed by jslachta** 2017-10-29 17:36 UTC

**Comment by urobasa** [comment] 2017-10-29 19:19
ok,thank you.

**Comment by leopucci** [comment] 2018-12-17 17:01
@jslachta, does anyone knows how to use chan_dongle with other versions? Because for me i have some trouble with one way audio on asterisk 13 and above. Do you guys know a solution for it?
Thanks in advance
Pucci

**Comment by micmac1** [comment] 2018-12-17 18:59
> @jslachta, does anyone knows how to use chan_dongle with other versions? Because for me i have some trouble with one way audio on asterisk 13 and above. Do you guys know a solution for it?
> Thanks in advance
> Pucci

Check [upstream](https://github.com/wdoekes/asterisk-chan-dongle). I had a glance at the open issues there but didn't see any open one-way audio report. So it could be a config issue. If you can verify it's not an issue with your config you could open an issue upstream. But chances are that it would only be resolved by either yourself or some other user who has the same issue.

In master we carry latest upstream version, in 18.06 we're only one [commit](https://github.com/wdoekes/asterisk-chan-dongle/commit/fd544d628d134cfe9cc2df6b5315298e93698664) behind, and that commit doesn't seem to have anything to do with one-way audio.

Regards,
Seb
