### ISSUE TITLE
asterisk (all versions): module load failures

### ISSUE THREAD

**Issue by mrzaphodb** [openwrt/telephony#77] opened 2015-07-03 16:43 UTC
I have encountered issues with the new Asterisk 11.18.0 in a fresh build of CC (r46160). Asterisk doesn't visibly load any modules and posts the following error messages in /var/log/asterisk/messages: 

[Jul 2 19:24:37] Asterisk 11.18.0 built by keith @ WildernetsXPS on a x86_64 running Linux on 2015-07-02 18:08:19 UTC [Jul 2 19:24:38] WARNING[2400] cel.c: Could not load cel.conf 
[Jul 2 19:24:38] NOTICE[2400] loader.c: 57 modules will be loaded. 
[Jul 2 19:24:38] WARNING[2400] loader.c: Error loading module 'res_musiconhold.so': Error loading shared library /usr/lib/asterisk/modules/res_musiconhold.so: No such file or directory 
[Jul 2 19:24:38] WARNING[2400] loader.c: Error loading module 'chan_sip.so': Error relocating /usr/lib/asterisk/modules/chan_sip.so: ast_websocket_read: symbol not found 
[Jul 2 19:24:39] WARNING[2400] loader.c: Error loading module 'chan_dahdi.so': Error relocating /usr/lib/asterisk/modules/chan_dahdi.so: ast_smdi_interface_unref: symbol not found 

I copied cel.conf out of the build directory and updated modules.conf so that it doesn't attempt to load res_musiconhold.so (since I don't have that selected in .config). This fixes the first two error messages. However, I already have res_smdi selected in the config and I don't have a config selection for res_http_websocket.

**Comment by matiasrivera** [comment] 2015-07-13 02:45
I have noticed that since Chaos Chalmer RC1 none of the 3 asterisk versions available (1.8, 11 and 13) load modules. I've been using CC trunk for at least 8 months and this is the first time I notice asterisk not fully working on trunk.
Log shows the amount of modules that will be loaded but the result is that none is actually working.
Matias

**Comment by matiasrivera** [comment] 2015-08-12 22:47
Hi Jiri,
  I'd like to know if you have any workarounds I can take to have asterisk back working on chaos calmer until this bug is fixed. I've tried to install the version from breaking barrier repository but I just can't make it work.

Thanks for your time.

Matias

**Comment by jslachta** [comment] 2015-08-13 10:26
Hi Matias,

as far as I know, the asterisk package should be fully working on uclibc (Chaos Calmer and older). For current trunk I have not found any solution to make it working yet. I am still heavypatching asterisk, I think I am close to it, but it does not work for me yet.

I am still working on it.

**Comment by matiasrivera** [comment] 2015-08-13 12:48
Hi Jiri,
  Thank you for your reply. I am pretty newbie in terms of OpenWrt so I have a quick question that maybe you can help me out with. I am on current trunk and definitively none of the 3 available asterisk versions (1.8, 11 and 13) are loading modules on my router. You mention that asterisk should be working on uclibc (Chaos Calmer and older). How is that different to trunk? How can I move to uclibc? Is it possible?

Thank again you for your help

Matias

**Comment by jslachta** [comment] 2015-08-13 14:56
Hi Matias,

if you are using "make menuconfig" for the configuration of openwrt buildroot,
you should select:

[*] Advanced configuration options (for developers) --->

then select:

[*] Toolchain Options --->

and then change

C library implementation (Use musl) --->

to uClibc.

Then asterisk will work. This is just a workaround until I fix the asterisk package for musl completely.

Jiri

Dne 13. 8. 2015 v 14:48 matiasrivera napsal(a):

**Comment by matiasrivera** [comment] 2015-08-14 13:37
Thanks again for your help Jiri,
  I have successfully re-compiled trunk with your suggestion. Now, when
trying to start asterisk from command line I get a segmentation fault. This
is my log. Do you have any idea of what might be wrong here?

root@openwrt:~# asterisk -c
Asterisk 13.4.0, Copyright (C) 1999 - 2014, Digium, Inc. and others.
Created by Mark Spencer <markster@digium.com>
Asterisk comes with ABSOLUTELY NO WARRANTY; type 'core show warranty' for
details.
This is free software, with components licensed under the GNU General Public
License version 2 and other licenses; you are welcome to redistribute it
under
certain conditions. Type 'core show license' for details.
=========================================================================
[ Initializing Custom Configuration Options ]
Unable to load config file 'stasis.conf'
Could not load Stasis configuration; using defaults
[Aug 14 13:33:09] ERROR[8177]: config_options.c:642 aco_process_config:
Unable to load config file 'cdr.conf'
[Aug 14 13:33:09] NOTICE[8177]: cdr.c:4049 process_config: Failed to
process CDR configuration; using defaults
[Aug 14 13:33:09] NOTICE[8177]: cdr.c:4152 cdr_toggle_runtime_options: CDR
simple logging enabled.
[Aug 14 13:33:09] ERROR[8177]: config_options.c:642 aco_process_config:
Unable to load config file 'cel.conf'
[Aug 14 13:33:09] NOTICE[8177]: cel.c:1755 ast_cel_engine_init: Failed to
process CEL configuration; using defaults
[Aug 14 13:33:09] NOTICE[8177]: loader.c:1364 load_modules: 25 modules will
be loaded.
[Aug 14 13:33:09] WARNING[8177]: loader.c:553 load_dynamic_module: Error
loading module 'res_musiconhold.so': File not found
[Aug 14 13:33:09] WARNING[8177]: loader.c:553 load_dynamic_module: Error
loading module 'res_musiconhold.so': File not found
[Aug 14 13:33:09] WARNING[8177]: loader.c:1079 load_resource: Module
'res_musiconhold.so' could not be loaded.
SIP channel loading...
[Aug 14 13:33:09] NOTICE[8177]: confbridge/conf_config_parser.c:2073
verify_default_profiles: Adding default_menu menu to app_confbridge
[Aug 14 13:33:09] WARNING[8177]: cdr_csv.c:107 load_config: unable to load
config: cdr.conf
[Aug 14 13:33:09] WARNING[8177]: pbx.c:12408 ast_context_verify_includes:
Context 'local' tries to include nonexistent context 'parkedcalls'
*Segmentation fault*

The list of installed packages is this

root@openwrt:~# opkg list *asterisk*
asterisk13 - 13.4.0-1
asterisk13-app-authenticate - 13.4.0-1
asterisk13-app-confbridge - 13.4.0-1
asterisk13-app-senddtmf - 13.4.0-1
asterisk13-bridge-builtin-features - 13.4.0-1
asterisk13-bridge-simple - 13.4.0-1
asterisk13-bridge-softmix - 13.4.0-1
asterisk13-cdr-csv - 13.4.0-1
asterisk13-chan-sip - 13.4.0-1
asterisk13-codec-a-mu - 13.4.0-1
asterisk13-codec-alaw - 13.4.0-1
asterisk13-codec-ulaw - 13.4.0-1
asterisk13-func-module - 13.4.0-1
asterisk13-pbx-ael - 13.4.0-1
asterisk13-res-agi - 13.4.0-1
luci-app-asterisk - git-15.216.69575-bb7ea3e-1

Thank you,

Matías

**Comment by redfox1977** [comment] 2015-09-08 11:39
Hi Jiri,
Is it posible asterisk compile again musli?

**Comment by matiasrivera** [comment] 2015-09-12 03:23
Hi Jiri,
  Sorry to bother again. I saw some changes have been commited to asterisk make files. Have you found any workaround for module loading?

Thanks

Matias

**Comment by redfox1977** [comment] 2015-10-01 17:18
Hello,
Give it a chance Asterisk 13 to compile with musli? I had last week tried Astersik start but unfortunately without success.

**Comment by arpena** [comment] 2015-12-02 21:14
Hi ! Is there any news on this?

**Comment by tangsoft** [comment] 2015-12-06 00:29
I am waiting on this as well.

**Comment by tangsoft** [comment] 2015-12-16 18:10
Is there anything could be ported from https://github.com/alpinelinux/aports/tree/master/main/asterisk?

**Comment by vteccomm** [comment] 2016-02-22 20:31
hi Jslachta

 i have tried all the things you mentioned but i m stuck below 

checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/uadmin/openwrt/build_dir/target-mips_34kc_musl-1.1.12/asterisk-11.20.0/menuselect':
configure: error: C compiler cannot create executables
See `config.log' for more details
make[3]: *** [/home/uadmin/openwrt/build_dir/target-mips_34kc_musl-1.1.12/asterisk-11.20.0/.configured_yyyyyyyy] Error 77
make[3]: Leaving directory `/home/uadmin/openwrt/feeds/telephony/net/asterisk-11.x'
make[2]: *** [package/feeds/telephony/asterisk-11.x/compile] Error 2
make[2]: Leaving directory `/home/uadmin/openwrt'
make[1]: *** [/home/uadmin/openwrt/staging_dir/target-mips_34kc_musl-1.1.12/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/uadmin/openwrt'
make: *** [world] Error 2

**Comment by jslachta** [comment] 2016-04-04 13:39
Hi, please try the latest fixes for asterisk13 and asterisk11. It should be fixed - everything runs fine on my test environment. If problem persists, please reopen.

**Comment by jslachta** [comment] 2016-04-12 07:26
I reopened the issue, the problem still persists.

**Comment by vteccomm** [comment] 2016-05-01 20:37
hi 
 

  i m trying to install codec_g729 in asterisk 11 asterisk 18 asterisk 13 from feeds but its not working asterisk works fine but once i install codec_g729 from feeds it doesn’t work 
i tried this on TL-WR1043ND and Archer C7 with openwrt 15.05 and openwrt 15.05.1. Please help me with that 

Thanks

**Comment by gergamel** [comment] 2016-08-17 12:33
Just wanted to add that I have confirmed this issue on an iMX6 target with MUSL std libs. Trying to match my working x86 install, I turned of autoload in /etc/asterisk/modules.conf and tried to load one module at a time. First one was res_sorcery_realtime.so and asterisk just hangs with nothing to stdout or stderr and nothing in the log file. Also needed to be killed with kill -9.

I can confirm that switching from MUSL to GLIBC has fixed the issue and Asterisk now loads all modules with no issues. It took about half a day to work through build errors caused by dodgy modules. Would love to know why the choice of stdlibs should cause such a difference.

**Comment by arpena** [comment] 2017-07-21 15:43
Any news on this? Nobody wants asterisk running on latest trunk without having to rebuild everything ourselves?

**Comment by vteccomm** [comment] 2017-07-21 19:08
well it works fine. whats the issue you facing?

**Comment by gergamel** [comment] 2017-07-24 02:36
@arpena My confirmation of this bug was with Asterisk 13.10.0. Looks like the head is now pointing to 13.15.0. Have you had a chance to test 13.15.0 with MUSL? It's possible the Asterisk guys may have fixed the underlying issue.

**Comment by arpena** [comment] 2017-07-24 15:47
I was testing with latest trunk, with the precompiled image and packages. Only asterisk11 is available and it fails with "Illegal instruction", but I think is unrelated to the modules problem. I'll try to compile trunk myself with MUSL and report back.
BTW, who decides which modules are precompiled?

**Comment by gergamel** [comment] 2017-07-25 02:41
@arpena No idea about the precompiled side of things. We build all our stuff in house anyway, so I didn't even know that was a thing. I am planning to try Asterisk 13.15.0 with MUSL on some new hardware at some point soon, but I'm not sure when I will actually get the time.

**Comment by micmac1** [comment] 2017-08-06 08:52
Hello @mrzaphodb @arpena @gergamel 

Can you try trunk, either compiled yourself or by getting a snapshot? If the issue can be reproduced please provide info how and the logs.

Thanks!
Sebastian

**Comment by jslachta** [comment] 2017-10-31 15:19
I am not able to reproduce this issue anymore. I am closing it. If anyone will find any similar issue, please reopen this ticket or fill a new one.

**Closed by jslachta** 2017-10-31 15:19 UTC
Labels: bug
